config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'

  get 'sessions' => 'sessions#index'
  post 'sessions' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  post 'users' => 'users#create'

  get 'events' => 'events#index'
  post 'attends' => 'attends#create'
  delete 'attends/:id' => 'attends#destroy'
  patch 'events/:id' => 'events#update'
  post 'events' => 'events#create', as: 'update-events'
  get 'events/:id' => 'events#edit'
  delete 'events/:id' => 'events#destroy'

end

app/models/attend.rb
class Attend < ActiveRecord::Base
  #validates :user, uniqueness: { scope: :attendend_event }

  belongs_to :event, class_name: 'Event', foreign_key: :event_id
  belongs_to :user, class_name: 'User', foreign_key: :user_id

  scope :user_event, ->(user_id, event_id) {
    where(user_id: user_id).where(event_id: event_id)
  }


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, :date, :location, :host,
    presence: true
  validates :state, length: {minimum:2, maximum:2}

  before_save :upcase_state

  belongs_to :host, class_name: 'User', foreign_key: :user_id

  has_many :attends, dependent: :destroy
  has_many :users, through: :attends, class_name: 'User', foreign_key: :event_id

  has_many :comments

  scope :state, ->(state) {
    includes(:attends).where(state: state).order(updated_at: :desc)
  }

  scope :other_state, ->(state) {
    includes(:attends).where.not(state: state).order(updated_at: :desc)
  }

  private

  def upcase_state
    self.state.upcase!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :first_name, :last_name, :email, :location, :state,
    presence: true
  validates :password,
    length: {minimum:8, allow_nil: true}
  validates :state, length: {minimum:2, maximum:2}
  validates :email, uniqueness: true, email: true

  has_many :hosted_events, class_name: 'Event', foreign_key: :user_id, dependent: :destroy
  has_many :attends, dependent: :destroy
  has_many :events, through: :attends, class_name: 'Event', foreign_key: :event_id
  has_many :comments

  before_save :upcase_state

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  private


  def upcase_state
    self.state.upcase!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  def redirect_no_auth
    if !session[:user_id]
      flash[:alert] = "Please Log In"
      redirect_to '/'
    end
  end


  def get_user
    User.find_by id: session[:user_id]
  end

end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController
  before_action :redirect_no_auth

  def create
    event = Event.find_by(id: params[:event_id])
    @attend = Attend.new(
      user: get_user,
      event: event
    )
    flash[:alert] = "Can't attend." if !@attend.valid?
    flash[:notice] = "Joined Event #{event.name}" if @attend.save
    redirect_to '/events'
  end

  def destroy
    @attend = Attend.find_by(id: params[:id]).destroy
    flash[:notice] = "Canceled Event #{@attend.event.name}"
    redirect_to '/events'
  end

  private

end

app/controllers/events_controller.rb
class EventsController <  ApplicationController
  before_action :redirect_no_auth
  def index
    get_events
    @new_event = Event.new
  end

  def destroy
    @event = Event.find_by(id: params[:id])
    if @event.host.id == session[:user_id]
      @event.destroy
      flash[:notice] = "Event #{@event.name} deleted."
    else
      flash[:alert] = "Event deletion failed"
    end
    redirect_to '/events'
  end

  def create
    @new_event = Event.new event_params
    @new_event.host = get_user
    if @new_event.save
      flash[:notice] = "Event #{@new_event.name} created"
      redirect_to '/events'
    else
      flash[:alert] = "Event #{@new_event.name} creation failed"
      get_events
      render "events/index"
    end
  end

  def edit
    @event = Event.find_by id: params[:id]
  end

  def update
    @event = Event.find_by id: params[:id]
    if @event.update(event_params)
      flash[:notice] = "Event #{@event.name} updated"
      redirect_to '/events'
    else
      fail
      flash[:alert] = "Event #{@event.name} update failed"
      render 'events/edit'
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :date, :location, :state)
  end

  def get_events
    @instate_events = Event.state get_user.state
    @outstate_events = Event.other_state get_user.state
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    @user = User.new
    @new_user = User.new
  end

  def create
    user = User.find_by_email(params[:user][:email])
    if user && user.authenticate(params[:user][:password])
      flash[:notice] = "Logged in #{user.full_name}"
      session[:user_id] = user.id
      session[:user_name] = "#{user.first_name} #{user.last_name}"
      flash[:notice] =  "login #{user.full_name}"
      redirect_to '/events'
    else
      @user = User.new
      @new_user = User.new
      flash[:alert] = 'Login Failed. pls check your account info.'
      render 'sessions/index'
    end
  end

  def destroy
    session.clear
    render text: "logged out #{session}"
  end

  private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new user_params
    if @user.save
      flash[:notice] = "created user"
      redirect_to '/'
    else
      @new_user = User.new
      render text: "failed #{@user.errors}"
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :location,
      :state,
      :password,
      :password_confirmation
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/events/_event_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Location</th>
      <th>Host</th>
      <th>Action / Status</th>
    </tr>
  </thead>
  <tbody>
    <% events.each do |event| %>
    <tr>
      <td><%= event.name %></td>
      <td><%= event.date %></td>
      <td><%= event.location %></td>
      <td><%= event.host.first_name %></td>
      <td>
        <% if event.host.id == session[:user_id] %>
          <form action="/events/<%= event.id %>" method="GET">
            <input type="submit" value="Edit">
          </form>
          <form action="/events/<%= event.id %>" method="POST">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
            <input type="hidden" name="_method" value="DELETE">
            <input type="submit" value="Delete">
          </form>
        <% elsif event.users.pluck(:id).include?(session[:user_id])  %>
          Joining
          <form action="/attends/<%= Attend.user_event(session[:user_id], event.id).last.id %>" method="POST">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
            <input type="hidden" name="_method" value="DELETE">
            <input type="submit" value="Cancel">
          </form>

        <% else %>
          <%= button_to 'Join', attends_path(event_id: event.id), method: 'POST' %>
        <% end %>


        <%= event.id %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_form.html.erb
<%= form_for event, class: 'form_horizontal' do |f| %>
  <div class="form-group">
    <%= f.label :name, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date, class: 'col-md-3 control-label' %>
    <div class="col-md-9">

      <%= f.text_field :date, data: { :date_format => 'YYYY/MM/DD' }, :class => 'form-control datetimepicker', placeholder: 'YYYY/MM/DD' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :location, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_field :location, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= f.text_field :state, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit title, class: 'btn btn-default' %>
  </div>

<% end %>

app/views/events/edit.html.erb
<div>
  <p>
    Edit Event
  </p>



  <%= form_tag "/events/#{@event.id}", class: 'form_horizontal' do  %>
  <input type="hidden" name="_method" value="PATCH">
  <div class="form-group">
    <%= label_tag :name, 'Name', class: 'col-md-3 control-label'%>
    <div class="col-md-9">
      <%= text_field_tag 'event[name]', @event.name, class: 'form-control'%>
    </div>
  </div>
  <div class="form-group">
    <%= label :date, class: 'col-md-3 control-label' %>
    <div class="col-md-9">

      <%= text_field_tag 'event[date]', @event.date, data: { :date_format => 'YYYY/MM/DD' }, :class => 'form-control datetimepicker', placeholder: 'YYYY/MM/DD' %>
    </div>
  </div>
  <div class="form-group">
    <%= label :location, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= text_field_tag 'event[location]', @event.location, class: 'form-control', value: @event.location %>
    </div>
  </div>
  <div class="form-group">
    <%= label :state, class: 'col-md-3 control-label' %>
    <div class="col-md-9">
      <%= text_field_tag 'event[state]', @event.state, class: 'form-control', value: @event.state %>
    </div>
  </div>
  <div class="form-group">
    <%= submit_tag 'update', class: 'btn btn-deult' %>
  </div>

<% end %>
</div>

app/views/events/index.html.erb
<div>
  <p>
  Here are some of the events at your state.
  </p>

  <%= render partial: 'event_list', locals: {events: @instate_events} %>
</div>
<div>

  <p>
  Here are some of the events on other states.
  </p>
  <%= render partial: 'event_list', locals: {events: @outstate_events} %>
</div>

<div>
  <p>
    Add Event
  </p>

  <%= render partial: 'form', locals: {event: @new_event, title: 'Add Event'} %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="contaner">

      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Welcome <%= session[:user_name] %></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="/logout">Log Out</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>


      <div class="container">
        <% if flash[:alert] %>
          <div class="alert alert-error">
            <%= flash[:alert] %>
          </div>
        <% end %>
      </div>
      <div class="container">
        <% if flash[:notice] %>
          <div class="alert alert-error">
            <%= flash[:notice] %>
          </div>
        <% end %>
      </div>

      <div class="container">
        <%= yield %>
      </div>


    </div>
  </body>
</html>